site_name: CoSy
site_description: Combinatory Synthesis
site_author: Constantin Chaumet, Andrej Dudenhefner, Felix Laarmann, Christoph Stahl
site_url: https://tudo-seal.github.io/cosy
repo_name: tudo-seal/cosy
repo_url: https://github.com/tudo-seal/cosy
edit_uri: blob/main/docs
copyright: 'Copyright &copy; <a href="https://github.com/Jekannadar">Constantin Chaumet</a>, <a href="https://github.com/mrhaandi">Andrej Dudenhefner</a>, <a href="https://github.com/FelixLaarmann">Felix Laarmann</a>, <a href="https://github.com/christofsteel">Christoph Stahl</a>: 2025-present'

docs_dir: docs
site_dir: site
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: docs/.overrides
  language: en
  favicon: assets/images/logo.svg
  icon:
    repo: fontawesome/brands/github
    logo: material/wall
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-off-outline
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Home:
    - About: index.md
    - Getting Started: quick-start.md
  - Examples: examples/
  - Guidelines:
      - Best Practice: guidelines/best-practice.md
      - Common Errors: guidelines/troubleshoot.md
  - Features:
      - Constraints: features/constraints.md
      - Advanced Users: features/advanced.md
  - Code Reference: reference/
  - About:
    - Authors: about/authors.md

watch:
- src/cosy
- examples

plugins:
  search: {}
  gen-files:
    scripts:
      - scripts/gen_reference_pages.py
      - scripts/gen_example_pages.py
  literate-nav:
    nav_file: SUMMARY.md
  minify:
    minify_html: true
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src, examples]
        options:
          show_root_heading: true
          show_root_full_path: false
          show_if_no_docstring: true
          show_signature_annotations: true
          show_bases: false
  git-revision-date-localized:
    type: date
    strict: false

markdown_extensions:
  - attr_list:
  - tables:
  - md_in_html:
  - toc:
        permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      guess_lang: false
      default_lang: cosy-py
  - pymdownx.inlinehilite:
      style_plain_text: cosy-py
  - pymdownx.snippets:
  - pymdownx.superfences:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tudo-seal/cosy