name: Check Docs

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: check-docs-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Full history for timestamps
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Build and Check
        run: hatch run docs:check