name: 'Check PR Rules for Main'

on:
  pull_request_target:
    types: [ opened ]
    branches:
      - main

jobs:
  pr-rules-main:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Close Pull Request and Comment if Violating
        uses: superbrothers/close-pull-request@v3
        if: ${{ !contains( github.head_ref, 'release/') && !contains( github.head_ref, 'hotfix/')}}
        with:
          comment: |
            :warning: You can only merge to main from a release or a hotfix branch. :warning:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail Job if Violating
        if: ${{ !contains( github.head_ref, 'release/') && !contains( github.head_ref, 'hotfix/')}}
        run: |
          echo "Reason: You can only merge to main from a release or a hotfix branch."
          exit 1
      - name: Succeed Job if not Violating
        if: ${{ contains( github.head_ref, 'release/') || contains( github.head_ref, 'hotfix/')}}
        run: |
          exit 0