name: 'Remind PR Rules'

on:
  pull_request:
    types: [ opened ]
    branches:
      - develop

jobs:
  pr-rules:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Comment Feature
        uses: thollander/actions-comment-pull-request@v3
        if: ${{ contains( github.head_ref, 'feature/') || contains( github.head_ref, 'bugfix/') }}
        with:
          message: |
            :information_source: FEATURE/BUGFIX BRANCH MERGING INTO DEVELOP. :information_source:
            
            :warning: Consider merging via squash. :warning: