name: Release CoSy

on:
  push:
    tags:
    - v*
  workflow_dispatch:

permissions:
  id-token: write

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  release:
    needs: [checks]
    environment: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Full history for timestamps
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Display Version
      run: hatch version

    - name: Build Package
      run: hatch build

    # Uses OpenID Connect
    - name: Publish Package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/